### PR TITLE
add predefined facility fulfillment option

### PR DESCRIPTION
**Pull request by rongboxu**

### CODE REVIEW

**Comment by rongboxu** [comment]
@ljwolf Hi Levi! I am currently rechecking the code changed in the fulfillment of predefined facility's capacity. The problem is that I find it's hard to separate my code from yours because the options I added are based on the predefined facility section you wrote earlier. In this case, maybe I should still make a pull request directly to you?

**Comment by ljwolf** [comment]
Hey! It's ok to open a new PR directly to pysal/spopt with your extra changes. That PR will have both what I've done and what you've added to it. That's totally ok. 

What @jGaboardi wanted is to have *your name* on the PR as the contributor, instead of mine, regardless of the authors of the individual commits 😄 

Does that make sense?

**Comment by rongboxu** [comment]
Oh Thank you!!! Now I understand! I will open a new PR when I finish this part!

**Comment by ljwolf** [comment]
I think this should be closed in favour of pysal/spopt#387

**Pull request closed without merging**
